api:
  base_url: "https://api.openalex.org/works?"
  per_page: 200

logging:
  level: INFO
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: 'output/gcr_research.log'

query_sets:
  - name: combined_gcr_query
    query_name: "Combined GCR and Resilience Query"
    url: "https://api.openalex.org/works?page=1&filter=default.search:(resilience+OR+mitigation+OR+resilient+OR+mitigate)+AND+(((%22global+catastrophic+risk%22+OR+%22existential+risk%22)+AND+(nuclear+OR+famine+OR+volcano+OR+pandemic))+OR+(%22nuclear+winter%22+OR+%22volcanic+winter%22+OR+%22abrupt+sunlight+reduction%22+OR+%22catastrophic+infrastructure+loss%22+OR+%22extreme+space+weather%22+OR+%22severe+space+weather%22+OR+(%22biological+threat%22+AND+pandemic)+OR+%22global+catastrophic+biological+risk%22+OR+%22engineered+pathogen%22+OR+%22global+food+supply+catastrophe%22))"

output:
  directory: 'output'
  ris_file: 'all_results.ris'